version: '2'
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
