name: Workflow

on:
  # Run on pushes to main..
  push:
    branches:
      - main
  # ..and any pull request.
  pull_request:

concurrency:
  group: env-${{ github.ref }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: yarn
      - run: yarn build
      - run: yarn test
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          path: coverage/lcov-report
      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: yarn
      - run: yarn build
      - run: yarn e2e
  deploy-alfajores:
    name: Deploy alfajores
    if: github.ref == 'refs/heads/main'
    needs:
      - e2e
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.ALFAJORES_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Deploy App
        run: ./deploy.sh -n alfajores
